/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsRevisionRouteImport } from './routes/agents.revision'
import { Route as AgentsLossRouteImport } from './routes/agents.loss'
import { Route as AgentsForecastRouteImport } from './routes/agents.forecast'
import { Route as AgentsExecutionRouteImport } from './routes/agents.execution'
import { Route as AgentsCreativeRouteImport } from './routes/agents.creative'
import { Route as AgentsCampaignRouteImport } from './routes/agents.campaign'

const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRevisionRoute = AgentsRevisionRouteImport.update({
  id: '/agents/revision',
  path: '/agents/revision',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsLossRoute = AgentsLossRouteImport.update({
  id: '/agents/loss',
  path: '/agents/loss',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsForecastRoute = AgentsForecastRouteImport.update({
  id: '/agents/forecast',
  path: '/agents/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsExecutionRoute = AgentsExecutionRouteImport.update({
  id: '/agents/execution',
  path: '/agents/execution',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsCreativeRoute = AgentsCreativeRouteImport.update({
  id: '/agents/creative',
  path: '/agents/creative',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsCampaignRoute = AgentsCampaignRouteImport.update({
  id: '/agents/campaign',
  path: '/agents/campaign',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/summary': typeof SummaryRoute
  '/agents/campaign': typeof AgentsCampaignRoute
  '/agents/creative': typeof AgentsCreativeRoute
  '/agents/execution': typeof AgentsExecutionRoute
  '/agents/forecast': typeof AgentsForecastRoute
  '/agents/loss': typeof AgentsLossRoute
  '/agents/revision': typeof AgentsRevisionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/summary': typeof SummaryRoute
  '/agents/campaign': typeof AgentsCampaignRoute
  '/agents/creative': typeof AgentsCreativeRoute
  '/agents/execution': typeof AgentsExecutionRoute
  '/agents/forecast': typeof AgentsForecastRoute
  '/agents/loss': typeof AgentsLossRoute
  '/agents/revision': typeof AgentsRevisionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/summary': typeof SummaryRoute
  '/agents/campaign': typeof AgentsCampaignRoute
  '/agents/creative': typeof AgentsCreativeRoute
  '/agents/execution': typeof AgentsExecutionRoute
  '/agents/forecast': typeof AgentsForecastRoute
  '/agents/loss': typeof AgentsLossRoute
  '/agents/revision': typeof AgentsRevisionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/how-it-works'
    | '/summary'
    | '/agents/campaign'
    | '/agents/creative'
    | '/agents/execution'
    | '/agents/forecast'
    | '/agents/loss'
    | '/agents/revision'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/how-it-works'
    | '/summary'
    | '/agents/campaign'
    | '/agents/creative'
    | '/agents/execution'
    | '/agents/forecast'
    | '/agents/loss'
    | '/agents/revision'
  id:
    | '__root__'
    | '/'
    | '/how-it-works'
    | '/summary'
    | '/agents/campaign'
    | '/agents/creative'
    | '/agents/execution'
    | '/agents/forecast'
    | '/agents/loss'
    | '/agents/revision'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HowItWorksRoute: typeof HowItWorksRoute
  SummaryRoute: typeof SummaryRoute
  AgentsCampaignRoute: typeof AgentsCampaignRoute
  AgentsCreativeRoute: typeof AgentsCreativeRoute
  AgentsExecutionRoute: typeof AgentsExecutionRoute
  AgentsForecastRoute: typeof AgentsForecastRoute
  AgentsLossRoute: typeof AgentsLossRoute
  AgentsRevisionRoute: typeof AgentsRevisionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/revision': {
      id: '/agents/revision'
      path: '/agents/revision'
      fullPath: '/agents/revision'
      preLoaderRoute: typeof AgentsRevisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/loss': {
      id: '/agents/loss'
      path: '/agents/loss'
      fullPath: '/agents/loss'
      preLoaderRoute: typeof AgentsLossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/forecast': {
      id: '/agents/forecast'
      path: '/agents/forecast'
      fullPath: '/agents/forecast'
      preLoaderRoute: typeof AgentsForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/execution': {
      id: '/agents/execution'
      path: '/agents/execution'
      fullPath: '/agents/execution'
      preLoaderRoute: typeof AgentsExecutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/creative': {
      id: '/agents/creative'
      path: '/agents/creative'
      fullPath: '/agents/creative'
      preLoaderRoute: typeof AgentsCreativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/campaign': {
      id: '/agents/campaign'
      path: '/agents/campaign'
      fullPath: '/agents/campaign'
      preLoaderRoute: typeof AgentsCampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HowItWorksRoute: HowItWorksRoute,
  SummaryRoute: SummaryRoute,
  AgentsCampaignRoute: AgentsCampaignRoute,
  AgentsCreativeRoute: AgentsCreativeRoute,
  AgentsExecutionRoute: AgentsExecutionRoute,
  AgentsForecastRoute: AgentsForecastRoute,
  AgentsLossRoute: AgentsLossRoute,
  AgentsRevisionRoute: AgentsRevisionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
